#!/bin/bash
cd ~/.nvim/
echo Installing plugins...
git submodule update --init --recursive
echo Done intsalling plugins...
echo Installing fonts...
fonts-install/install.sh
echo Done installing fonts...
echo Note: Some configuration requires external applications:
echo \'xclip\', \'the_silver_searcher\', \'ruby\', then \'sudo su -c \"gem install sass\"\'
