#!/bin/bash
cd ~/.nvim/
echo Installing plugins...
git submodule update --init --recursive
echo Done intsalling plugins...
echo Installing fonts...
fonts-install/install.sh
echo Done installing fonts...
